# Generated by Django 3.1.5 on 2021-01-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_company_director_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_bio',
            field=models.CharField(max_length=300, null=True, verbose_name='Βιογραφικό/Πληροφορίες'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_dateOfBirth',
            field=models.DateField(null=True, verbose_name='Ημερομηνία γέννησης'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_placeOfBirth',
            field=models.CharField(max_length=30, null=True, verbose_name='Τόπος Γέννησης'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_bio',
            field=models.TextField(null=True, verbose_name='Βιογραφικό/Πληροφορίες'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_dateOfBirth',
            field=models.DateField(null=True, verbose_name='Ημερομηνία γέννησης'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_gender',
            field=models.CharField(max_length=20, verbose_name='Γένος'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_placeOfBirth',
            field=models.CharField(max_length=30, null=True, verbose_name='Τόπος Γέννησης'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movies.Actor', verbose_name='Ηθοποιοί'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.company', verbose_name='Εταιρία Παραγωγής'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.director', verbose_name='Σκηνοθέτης'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.genre', verbose_name='Είδος'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rate',
            field=models.FloatField(null=True, verbose_name='Βαθμολογία_IMBD'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere_date',
            field=models.DateField(null=True, verbose_name='Ημερομηνία Πρεμίερας'),
        ),
    ]
