# Generated by Django 3.1.5 on 2021-01-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210105_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=20, null=True, verbose_name='Γλώσσα'),
        ),
    ]
