# Generated by Django 3.1.5 on 2021-01-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_description', models.CharField(max_length=10, verbose_name='Φύλο')),
            ],
            options={
                'verbose_name': 'Φύλο',
                'verbose_name_plural': 'Φύλα',
                'db_table': 'gender',
                'ordering': ['gender_description'],
            },
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.gender', verbose_name='Φύλο'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.gender', verbose_name='Φύλο'),
        ),
    ]
