# Generated by Django 2.2.2 on 2021-01-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['subject'], 'verbose_name': 'Επικοινωνία', 'verbose_name_plural': 'Επικοινωνία'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
