# Generated by Django 3.1.5 on 2021-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210105_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_bio',
            field=models.TextField(null=True, verbose_name='Βιογραφικό/Πληροφορίες'),
        ),
    ]
