# Generated by Django 2.2.2 on 2021-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210129_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('GR', 'Greek'), ('EN', 'English')], max_length=20, null=True, verbose_name='Γλώσσα'),
        ),
    ]
