# Generated by Django 3.1.5 on 2021-01-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210105_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Φώτο Ηθοποιός'),
        ),
    ]
