# Generated by Django 2.2.2 on 2021-01-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210131_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('GR', 'Greek')], max_length=20, null=True, verbose_name='Γλώσσα'),
        ),
    ]
