# Generated by Django 2.2.2 on 2021-02-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210131_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('GR', 'Greek'), ('EN', 'English')], max_length=20, null=True, verbose_name='Γλώσσα'),
        ),
    ]
