# Generated by Django 2.2.2 on 2021-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210201_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('GR', 'Greek')], max_length=20, null=True, verbose_name='Γλώσσα'),
        ),
    ]
